version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Verifying Node.js and npm versions:"
      - node -v && npm -v
      - echo "Installing project dependencies..."
      - npm ci

  build:
    commands:
      - echo "DEBUG - Checking STAGE environment variable..."
      - echo "STAGE value is - '$STAGE'"
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt -t src/
      - echo "Zipping the Lambda function code..."
      - cd src && zip -r ../patient_record_service.zip . && cd ..
      - echo "Deploying to AWS Lambda using Serverless..."
      - npx serverless deploy --stage $STAGE
      - echo "Publishing Lambda function version..."
      - LAMBDA_VERSION=$(aws lambda publish-version \
          --function-name patient-record-service-$STAGE \
          --query Version \
          --output text)
      - echo "Published Lambda Version - $LAMBDA_VERSION"
      - echo "Updating AppSpec file with STAGE and VERSION..."
      - sed -i "s/\${STAGE}/$STAGE/g; s/\${VERSION}/$LAMBDA_VERSION/g" appspec.yml
      - echo "Final appspec.yml file content:"
      - cat appspec.yml

artifacts:
  files:
    - appspec.yml
    - patient_record_service.zip
  discard-paths: yes