version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t src/

  build:
    commands:
      - echo "Packaging Lambda function..."
      - cd src && zip -r ../patient_record_service.zip .
      - cd ..
      - echo "Publishing Lambda function version..."
      - aws lambda update-function-code --function-name patient-record-service-$STAGE --zip-file fileb://patient_record_service.zip
      - LAMBDA_VERSION=$(aws lambda publish-version --function-name patient-record-service-$STAGE --query Version --output text)
      - echo "Replacing STAGE and VERSION in appspec.yml..."
      - sed "s/\${STAGE}/$STAGE/g; s/\${VERSION}/$LAMBDA_VERSION/g" appspec.yml > appspec-resolved.yml
      - mv appspec-resolved.yml appspec.yml
      - echo "Final appspec.yml:"
      - cat appspec.yml

artifacts:
  files:
    - appspec.yml
    - patient_record_service.zip
  discard-paths: yes