version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t src/
  build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/ || echo "Tests failed. Check output for details."
      - echo "Packaging Lambda function..."
      - cd src && zip -r ../patient_record_service.zip .
      - cd ..
      - echo "------------------------------------------"
      - echo "DEBUG: Checking STAGE environment variable"
      - echo "STAGE value is: $STAGE"
      - echo "------------------------------------------"
      - echo "Replacing STAGE placeholder in appspec.yml..."
      - sed "s/\${STAGE}/$STAGE/g" appspec.yml > appspec-resolved.yml
      - mv appspec-resolved.yml appspec.yml
      - echo "Generated appspec.yml file:"
      - cat appspec.yml
      - echo "Listing files in the build directory:"
      - ls -la
artifacts:
  files:
    - appspec.yml                # Ensure the final file is named appspec.yml
    - patient_record_service.zip
  discard-paths: yes             # Ensures files are placed in the root of the artifact