version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      commands:
        - echo "============================================="
        - echo "Installing Node.js via NVM for reliability..."
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
          export NVM_DIR="$HOME/.nvm" && \
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && \
          nvm install 18 && \
          nvm use 18
        - echo "Verifying Node.js and npm versions:"
        - node -v && npm -v
        - echo "============================================="
        - echo "Clearing NPM cache to avoid archive issues..."
        - npm cache clean --force
        - echo "Retrying installation of Serverless Framework..."
        - npm install -g serverless@3.38.0 || npm install -g serverless@3.38.0
        - echo "Serverless Framework installed successfully!"
        - serverless --version
  build:
    commands:
      - echo "============================================="
      - echo "DEBUG - Checking STAGE environment variable..."
      - echo "STAGE value is - '$STAGE'"
      - echo "============================================="
      - echo "Zipping the Lambda function code..."
      - cd src && zip -r ../patient_record_service.zip . && cd ..
      - echo "---------------------------------------------"
      - echo "Deploying to AWS Lambda using Serverless..."
      - serverless deploy --stage $STAGE
      - echo "---------------------------------------------"
      - echo "Publishing Lambda function version..."
      - LAMBDA_VERSION=$(aws lambda publish-version \
          --function-name patient-record-service-$STAGE \
          --query Version \
          --output text)
      - echo "Published Lambda Version - $LAMBDA_VERSION"
      - echo "============================================="
      - echo "Updating AppSpec file with STAGE and VERSION..."
      - sed "s/\${STAGE}/$STAGE/g; s/\${VERSION}/$LAMBDA_VERSION/g" appspec.yml > appspec-resolved.yml
      - mv appspec-resolved.yml appspec.yml
      - echo "Final appspec.yml file content:"
      - cat appspec.yml
      - echo "Build stage completed successfully."

artifacts:
  files:
    - appspec.yml
    - patient_record_service.zip
  discard-paths: yes