version: 0.2

env:
  variables:
    DOCKER_USERNAME: "channa316"  # Docker Hub username
    DOCKER_PASSWORD: "3ezvNbGcG8EhF$m"  # Docker Hub password

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $DOCKER_USERNAME/patient-record-service:latest .
      - echo "Tagging Docker image with commit hash..."
      - docker tag $DOCKER_USERNAME/patient-record-service:latest $DOCKER_USERNAME/patient-record-service:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKER_USERNAME/patient-record-service:latest
      - docker push $DOCKER_USERNAME/patient-record-service:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Deploying to Kubernetes..."
      - kubectl apply -f k8s-deployment.yml

artifacts:
  files:
    - k8s-deployment.yml
