version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Verifying Node.js version:"
      - node -v
      - echo "Installing yarn..."
      - npm install -g yarn
      - yarn --version
      - echo "Creating package.json file..."
      - |
        cat << EOF > package.json
        {
          "name": "patient-record-service",
          "version": "1.0.0",
          "description": "Patient Record Service",
          "dependencies": {
            "serverless": "3.38.0",
            "serverless-deployment-bucket": "^1.6.0"
          }
        }
        EOF
      - echo "Installing project dependencies..."
      - yarn install --no-lockfile

  build:
    commands:
      - echo "DEBUG - Checking STAGE environment variable..."
      - echo "STAGE value is - '$STAGE'"
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt -t src/
      - echo "Zipping the Lambda function code..."
      - cd src && zip -r ../patient_record_service.zip . && cd ..
      - echo "Deploying to AWS Lambda using Serverless..."
      - yarn serverless deploy --stage $STAGE
      - echo "Publishing Lambda function version..."
      - LAMBDA_VERSION=$(aws lambda publish-version \
          --function-name patient-record-service-$STAGE \
          --query Version \
          --output text)
      - echo "Published Lambda Version - $LAMBDA_VERSION"
      - echo "Updating AppSpec file with STAGE and VERSION..."
      - sed -i "s/\${STAGE}/$STAGE/g; s/\${VERSION}/$LAMBDA_VERSION/g" appspec.yml
      - echo "Final appspec.yml file content:"
      - cat appspec.yml

artifacts:
  files:
    - appspec.yml
    - patient_record_service.zip
  discard-paths: yes

