version: 0.2

env:
  variables:
    DOCKER_USERNAME: "channa316"
    DOCKER_PASSWORD: "3ezvNbGcG8EhF$m"
    CLUSTER_NAME: "meditrack-cluster"
    REGION: "ap-south-1"

phases:
  install:
    commands:
      - echo "Starting setup..."
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $DOCKER_USERNAME/patient-record-service:latest .
      - docker tag $DOCKER_USERNAME/patient-record-service:latest $DOCKER_USERNAME/patient-record-service:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKER_USERNAME/patient-record-service:latest
      - docker push $DOCKER_USERNAME/patient-record-service:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Configuring kubectl for EKS..."
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
      - kubectl config view
      - kubectl config current-context
      - echo "Checking kubectl connectivity..."
      - kubectl get nodes
      - echo "Applying RBAC configuration for CodeBuild..."
      - kubectl apply -f k8s/rbac.yml
      - echo "Updating deployment YAML with image tag..."
      - sed -i "s|channa316/patient-record-service:latest|channa316/patient-record-service:$CODEBUILD_RESOLVED_SOURCE_VERSION|g" k8s-deployment.yml
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f k8s-deployment.yml --validate=false
      - echo "Verifying deployment..."
      - kubectl rollout status deployment/patient-record-service

artifacts:
  files:
    - k8s-deployment.yml
