version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "============================================="
      - echo "Installing Node.js LTS version..."
      - curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -  # Install Node.js 18.x LTS
      - yum install -y nodejs
      - echo "Verifying Node.js and npm versions:"
      - node -v
      - npm -v
      - echo "============================================="
      - echo "Clearing NPM cache to avoid archive issues..."
      - npm cache clean --force
      - echo "Installing Serverless Framework v3.38.0..."
      - npm install -g serverless@3.38.0
      - echo "============================================="
  build:
    commands:
      - echo "============================================="
      - echo "DEBUG - Checking STAGE environment variable..."
      - echo "STAGE value is - '$STAGE'"
      - echo "============================================="
      - echo "Zipping the Lambda function code..."
      - cd src && zip -r ../patient_record_service.zip . && cd ..
      - echo "---------------------------------------------"
      - echo "Deploying to AWS Lambda using Serverless..."
      - serverless deploy --stage $STAGE
      - echo "---------------------------------------------"
      - echo "Publishing Lambda function version..."
      - LAMBDA_VERSION=$(aws lambda publish-version \
          --function-name patient-record-service-$STAGE \
          --query Version \
          --output text)
      - echo "Published Lambda Version - $LAMBDA_VERSION"
      - echo "============================================="
      - echo "Updating AppSpec file with STAGE and VERSION..."
      - sed "s/\${STAGE}/$STAGE/g; s/\${VERSION}/$LAMBDA_VERSION/g" appspec.yml > appspec-resolved.yml
      - mv appspec-resolved.yml appspec.yml
      - echo "Final appspec.yml file content:"
      - cat appspec.yml
      - echo "Build stage completed successfully."

artifacts:
  files:
    - appspec.yml
    - patient_record_service.zip
  discard-paths: yes