version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t src/
  build:
    commands:
      - echo "Packaging Lambda function..."
      - cd src && zip -r ../patient_record_service.zip .
      - echo "Copying appspec.yml for CodeDeploy..."
      - cp ../appspec.yml .
artifacts:
  files:
    - appspec.yml
    - patient_record_service.zip