version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t src/
  build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/ || echo "Tests failed. Check output for details."
      - echo "Packaging Lambda function..."
      - cd src && zip -r ../patient_record_service.zip .
      - echo "Replacing STAGE placeholder in appspec.yml..."
      - sed "s/\${STAGE}/$STAGE/g" ../appspec.yml > appspec.yml
artifacts:
  files:
    - appspec.yml
    - patient_record_service.zip