service: patient-record-service

provider:
  name: aws
  runtime: python3.11
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket}
  environment:
    STAGE: ${self:provider.stage}

functions:
  patientServiceHandler:
    handler: patient_record_service.lambda_handler
    name: patient-record-service-${self:provider.stage}
    description: "Patient Record Service Lambda for ${self:provider.stage} environment"
    events:
      - http:
          path: patient
          method: any
          cors: true

package:
  individually: true
  exclude:
    - "node_modules/**"
    - ".git/**"
    - "buildspec.yml"
    - "tests/**"
    - "*.md"

plugins:
  - serverless-deployment-bucket

custom:
  deploymentBucket: patient-record-service-deployments-${self:provider.stage}